import room1 from '@/public/room-1.jpg';
import room2 from '@/public/room-2.jpg';
import room3 from '@/public/room-3.png';
import room4 from '@/public/room-4.png';

export const products = [
  {
    id: 1,
    name: 'Suite avec 2 toilettes',
    status: 'Disponible',
    href: '#',
    imageSrc: room1,
    imageAlt: 'Suite avec 2 toilettes',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'suite',
  },
  {
    id: 2,
    name: 'Chambre simple',
    status: 'Maintenance',
    href: '#',
    imageSrc: room2,
    imageAlt: 'Chambre simple',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'simple',
  },
  {
    id: 3,
    name: 'Chambre bien équipée',
    status: 'reservé',
    href: '#',
    imageSrc: room3,
    imageAlt: 'Chambre bien équipée',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'luxe',
  },
  {
    id: 4,
    name: 'Chambre sans cuisine',
    status: 'Maintenance',
    href: '#',
    imageSrc: room4,
    imageAlt: 'Chambre sans cuisine',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'suite',
  },
  {
    id: 5,
    name: 'Suite avec 2 toilettes',
    status: 'Disponible',
    href: '#',
    imageSrc: room1,
    imageAlt: 'Suite avec 2 toilettes',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'suite',
  },
  {
    id: 6,
    name: 'Chambre simple',
    status: 'Maintenance',
    href: '#',
    imageSrc: room2,
    imageAlt: 'Chambre simple',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'suite',
  },
  {
    id: 7,
    name: 'Chambre bien équipée',
    status: 'reservé',
    href: '#',
    imageSrc: room3,
    imageAlt: 'Chambre bien équipée',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'luxe',
  },
  {
    id: 8,
    name: 'Chambre sans cuisine',
    status: 'Maintenance',
    href: '#',
    imageSrc: room4,
    imageAlt: 'Chambre sans cuisine',
    price: '$140',
    description : 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category:'simple',
  },

];
